### ISSUE TITLE
Settings page blank in flows

### ISSUE THREAD

**Issue by RebbePod** [tprouvot/Salesforce-Inspector-reloaded#556]
**Make sure to read the troubleshooting section before creating an issue**

- [x] I've read the [common issues](https://tprouvot.github.io/Salesforce-Inspector-reloaded/troubleshooting/) and the one I'm about to create is not one of those documented.
- [x] I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already fixed.

**Describe the bug**
This only happens in the flow builder and only at random times, usually refreshing the apge fixes it, but today had the issue again and the refresh didn't help. I did a hard refresh a few minutes later and it worked again. 

(I have third party cookies enabled)

**To Reproduce**
Unfortunately I don't know

**Expected behavior**
I shoudl see the side tab 

**Screenshots**
<img width="461" alt="image" src="https://github.com/user-attachments/assets/b9a89a99-18f1-4e6d-b556-d2f33e3c30b9">

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version v1.24

**Additional context**

**Comment by tprouvot** [comment]
I @RebbePod  since I Can't reproduce the issue, it's pretty difficult to analyse and fix.
When this happen, do you have any error in the chrome dev console ?

**Comment by RebbePod** [comment]
@tprouvot when it happens again I'll take a look

**Comment by RebbePod** [comment]
@tprouvot I was somewhat able to reproduce by going to a field which is used by a few flows and opening the flow from the "Where is this used?" page. (usually it shows properly but occasionally it doesn't, gotta try a few times).

here is the console logs, i'm getting this when it works too, so don't think it's related
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentElement')
    at lex.js:1:70663
    at s (lex.js:1:60610)
    at Generator._invoke (lex.js:1:60398)
    at Generator.next (lex.js:1:61035)
    at c (lex.js:1:70195)
    at i (lex.js:1:70848)
beaconLib.BeaconLibrary.js:41 `

**Comment by RebbePod** [comment]
@tprouvot still happens once in a while, I suspect it's one of the other chrome extensions but have no way of knowing. Still only happens when in a flow.
